#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$1" == "-?" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Generate TLS certificate files for Hazelcast and Mosquitto

DESCRIPTION
   Generates TLS certificate files for Hazelcast and Mosquitto in the following directory.

   $APP_DIR/tls

   This command is interactive. It will ask for the CA private key password.

EOF
exit
fi

if [ ! -d "$APP_DIR/tls" ]; then
   mkdir -p $APP_DIR/tls/mosquitto/ca
   mkdir -p $APP_DIR/tls/mosquitto/broker
   mkdir -p $APP_DIR/tls/mosquitto/client
fi

#
# ------- Mosquitto --------
#

# Generate CA certificates
pushd $APP_DIR/tls/mosquitto/ca > /dev/null 2>&1
openssl req -new -x509 -days 3650 -extensions v3_ca -keyout mosquitto-ca.key -out mosquitto-ca.pem -subj "/C=US/ST=NY/L=New York/O=MyCo/CN=myca"
popd > /dev/null 2>&1

# Generate Broker certificates
pushd $APP_DIR/tls/mosquitto/broker > /dev/null 2>&1
openssl genrsa -traditional -out broker.key 2048
openssl req -out broker.csr -key broker.key -new -subj "/C=US/ST=NY/L=New York/O=MyCo/CN=padogrid1"
openssl x509 -req -in broker.csr -CA ../ca/mosquitto-ca.pem -CAkey ../ca/mosquitto-ca.key -CAcreateserial -out broker.crt -days 3650
rm broker.csr
cat broker.key broker.crt > mosquitto-openssl.pem
popd > /dev/null 2>&1

# Generate client certificates
pushd $APP_DIR/tls/mosquitto/client > /dev/null 2>&1
openssl genrsa -traditional -out client.key 2048
openssl req -out client.csr -key client.key -new -subj "/C=US/ST=CT/L=CT/O=SELFSIGNED/CN=padogrid2"
openssl x509 -req -in client.csr -CA ../ca/mosquitto-ca.pem -CAkey ../ca/mosquitto-ca.key -CAcreateserial -out client.crt -days 3650
rm client.csr
popd > /dev/null 2>&1

# Generate non-traditional hazelcast client certificates
pushd $APP_DIR/tls/mosquitto/client > /dev/null 2>&1
openssl genrsa -out hazelcast-client.key 2048
openssl req -out hazelcast-client.csr -key hazelcast-client.key -new -subj "/C=US/ST=CT/L=CT/O=SELFSIGNED/CN=padogrid2"
openssl x509 -req -in hazelcast-client.csr -CA ../ca/mosquitto-ca.pem -CAkey ../ca/mosquitto-ca.key -CAcreateserial -out hazelcast-client.crt -days 3650
rm hazelcast-client.csr
popd > /dev/null 2>&1

echo ""
echo "Certificates generated in the ../tls/ directory."
echo ""
pushd $APP_DIR > /dev/null 2>&1
tree tls
popd > /dev/null 2>&1
